repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-json
    - id: check-toml
    - id: check-xml
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-executables-have-shebangs
    - id: mixed-line-ending
    - id: check-added-large-files
    args: ['--maxkb=500']

-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.4.0
    hooks:
    - id: conventional-pre-commit
    stages: [commit-msg]

-   repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
    - id: go-fmt
    - id: go-imports
    - id: go-vet-mod
    - id: go-mod-tidy
    - id: go-unit-tests
    - id: go-build-mod
    - id: go-mod-vendor-check
    exclude: '^vendor/'

-   repo: https://github.com/securecodewarrior/github-action-add-sarif
    rev: v1.1.2
    hooks:
    - id: sarif-fmt
    files: '\.sarif$'
