default_install_hook_types:
    - pre-commit
    - commit-msg

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-json
    - id: check-toml
    - id: check-xml
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-executables-have-shebangs
    - id: mixed-line-ending
    - id: check-added-large-files
    args: ['--maxkb=500']

-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
    - id: conventional-pre-commit
    stages: [commit-msg]

-   repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
    - id: go-fmt
    - id: go-vet
    - id: go-lint
    - id: go-imports
    - id: validate-toml
    - id: no-go-testing
    - id: golangci-lint
    - id: go-critic
    - id: go-unit-tests
    - id: go-build
    - id: go-mod-tidy
    - id: go-cyclo
    args: [-over=15]
    exclude: '^vendor/'
